apiVersion: v1
kind: Pod
metadata:
  name: busybox-secret-env
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    env:
    - name: MEU_USERNAME
      valueFrom:
        secretKeyRef:
          name: meu-literal
          key: user
    - name: MEU_PASSWORD
      valueFrom:
        secretKeyRef:
          name: meu-literal
          key: password
