apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    name: busy
    command:
      - sleep
      - "3600"
    volumeMounts:
    - mountPath: /tmp/secrets
      name: meu-secret
  volumes:
  - name: meu-secret
    secret:
      secretName: minha-senha
