# docker build --no-cache -f [DOCKERFILE_NAME] -t [IMAGE_NAME]:[VERSAO] . ; contrucao da imagem

# docker container run -d -p [PORTA_HOST]:[PORTA_CONTAINER] [IMAGE_NAME]:[VERSAO] ; execucao do container

FROM debian
MAINTAINER caio ferreira - abreuferr@gmail.com
RUN apt-get update && apt-get install -y nginx && apt-get clean && rm -rf /var/lib/apt/lists/*
COPY html/index.html /var/www/html/
ENTRYPOINT ["/usr/sbin/nginx","-g","daemon off;"]
EXPOSE 80
