############################################################
# Dockerfile - Volume
#
#############################################################

# imagem a ser utilizada para construir o container
FROM debian

# mantenedor do Dockerfile
MAINTAINER caio abreu ferreira - abreuferr@gmail.com

# Criar um volume
VOLUME /dockerVolume
