# docker build --no-cache -f [DOCKERFILE_NAME] -t [IMAGE_NAME]:[VERSAO] . ; contrucao da imagem

# docker container run -d -p [PORTA_HOST]:[PORTA_CONTAINER] [IMAGE_NAME]:[VERSAO] ; execucao do containe

# imagem padrao
FROM debian:stretch

# mantenedor do Dockerfile
MAINTAINER caio abreu ferreira - abreuferr@gmail.com

# Exibir mensadem de atualicao do debian
CMD "echo" "Atualizando o GNU/Linux Debian"

# Atualizar o repositorio e atualizar a distribuicao
RUN apt-get update && apt-get upgrade && apt-get clean
