# docker build --no-cache -f [DOCKERFILE_NAME] -t [IMAGE_NAME]:[VERSAO] . ; contrucao da imagem
# docker container run -d -p [PORTA_HOST]:[PORTA_CONTAINER] [IMAGE_NAME]:[VERSAO] ; execucao do container

FROM debian

LABEL author="caio ferreira - abreuferr@gmail.com"
LABEL version="1.0"

RUN apt-get update && \
    apt-get install -y nginx && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# sera criado um volume no host, /var/lib/docker/volumes/[HASH]/_data/
VOLUME /var/www/html/
ADD html/index.html /var/www/html/
WORKDIR /var/www/html


ENTRYPOINT ["/usr/sbin/nginx"]
CMD ["-g","daemon off;"]
EXPOSE 80
