# docker build --no-cache -f [DOCKERFILE_NAME] -t [IMAGE_NAME]:[VERSAO] . ; contrucao da imagem

# docker container run -d -p [PORTA_HOST]:[PORTA_CONTAINER] [IMAGE_NAME]:[VERSAO] ; execucao do containe

# imagem - ultima versao estavel do debian
FROM debian:latest

# mantenedor da imagem
MAINTAINER caio abreu ferreira - abreuferr@gmail.com

# Atualizar o repositorio e atualizar a distribuicao
RUN apt-get update && apt-get upgrade -y && apt-get install -y nginx -y && apt-get clear

# expor a porta 80 do container
EXPOSE 80

# inicializar o nginx no container
CMD ["nginx", "-g", "daemon off;"]
