# imagem - ultima versao estavel do debian
FROM debian:latest

# mantenedor da imagem
MAINTAINER caio abreu ferreira - abreuferr@gmail.com

# Atualizar o repositorio e atualizar a distribuicao
RUN apt-get update && \
    apt-get upgrade -y

# Instalacao do nginx
RUN apt-get install -y nginx -y &&  \
    rm -rf /var/lib/apt/lists/*

# Variavel
ENV PROJECT_DIR=/var/www/html/

# copiar o arquivo index.html do host para a imagem
COPY html/index.html $PROJECT_DIR

# expor a porta 80 do container
EXPOSE 80

# inicializar o nginx no container
CMD ["nginx", "-g", "daemon off;"]
